# Generated by Django 5.2.13 on 2026-04-26 18:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('medication', models.TextField(blank=True)),
                ('diagnosis_notes', models.TextField(blank=True)),
                ('ai_differential', models.TextField(blank=True)),
                ('ai_medical', models.TextField(blank=True)),
                ('next_appointment', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('with_doctor', 'With Doctor'), ('done', 'Done')], default='waiting', max_length=20)),
                ('checked_in_at', models.DateTimeField(blank=True, help_text='Set automatically when the visit is created via check-in.', null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
            ],
            options={
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
    ]
