# Generated by Django 5.2.13 on 2026-04-26 18:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', 'Only alphabets and spaces are allowed.')])),
                ('date_of_birth', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], max_length=25)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=10)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='patient_photos/')),
                ('mobile_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a valid 10-digit mobile number.')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('alternate_contact', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a valid 10-digit mobile number.')])),
                ('address', models.TextField()),
                ('pin_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Enter a valid 6-digit PIN code.')])),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('id_type', models.CharField(choices=[('Aadhar', 'Aadhar'), ('PAN', 'PAN'), ('Passport', 'Passport')], max_length=20)),
                ('id_number', models.CharField(default='', max_length=20)),
                ('insurance_provider', models.CharField(choices=[('Star Health', 'Star Health'), ('LIC', 'LIC'), ('HDFC Ergo', 'HDFC Ergo'), ('Bajaj Allianz', 'Bajaj Allianz'), ('New India Assurance', 'New India Assurance'), ('None', 'None')], default='None', max_length=50)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientMedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor_notes', models.TextField(blank=True, null=True)),
                ('medical_conditions', models.JSONField(blank=True, default=list)),
                ('condition_details', models.TextField(blank=True, null=True)),
                ('current_medications', models.JSONField(blank=True, default=list)),
                ('past_medications', models.TextField(blank=True, null=True)),
                ('surgeries', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('family_history', models.TextField(blank=True, null=True)),
                ('smoking', models.CharField(choices=[('Never', 'Never'), ('Occasionally', 'Occasionally'), ('Regular', 'Regular')], max_length=20)),
                ('alcohol', models.CharField(choices=[('Never', 'Never'), ('Social', 'Social'), ('Regular', 'Regular')], max_length=20)),
                ('exercise', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Rare', 'Rare')], max_length=20)),
                ('height_cm', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('confirm_information', models.BooleanField(default=False)),
                ('agree_data_policy', models.BooleanField(default=False)),
                ('agree_research', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_histories', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Patient Medical History',
                'verbose_name_plural': 'Patient Medical Histories',
            },
        ),
    ]
