# Generated by Django 5.2.13 on 2026-04-29 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='doctors/photos/')),
                ('specialization', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Orthopedics', 'Orthopedics'), ('Pediatrics', 'Pediatrics'), ('Dermatology', 'Dermatology'), ('Radiology', 'Radiology'), ('General Medicine', 'General Medicine'), ('Surgery', 'Surgery'), ('Gynecology', 'Gynecology'), ('Psychiatry', 'Psychiatry'), ('ENT', 'ENT'), ('Ophthalmology', 'Ophthalmology'), ('Oncology', 'Oncology'), ('Urology', 'Urology'), ('Nephrology', 'Nephrology'), ('Other', 'Other')], max_length=100)),
                ('qualification', models.CharField(max_length=200)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('chamber_number', models.CharField(blank=True, max_length=20)),
                ('days_available', models.CharField(choices=[('Mon-Fri', 'Monday to Friday'), ('Mon-Sat', 'Monday to Saturday'), ('Tue-Sat', 'Tuesday to Saturday'), ('Mon-Wed-Fri', 'Monday, Wednesday, Friday'), ('Tue-Thu-Sat', 'Tuesday, Thursday, Saturday'), ('Weekends', 'Weekends Only'), ('All Days', 'All Days')], max_length=50)),
                ('shift_timings', models.CharField(choices=[('Morning (8AM - 2PM)', 'Morning (8AM - 2PM)'), ('Afternoon (2PM - 8PM)', 'Afternoon (2PM - 8PM)'), ('Evening (4PM - 10PM)', 'Evening (4PM - 10PM)'), ('Night (10PM - 6AM)', 'Night (10PM - 6AM)'), ('Full Day (8AM - 8PM)', 'Full Day (8AM - 8PM)')], max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('is_first_login', models.BooleanField(default=True)),
                ('temp_password', models.CharField(blank=True, max_length=20)),
                ('otp_secret', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('assigned_patients', models.ManyToManyField(blank=True, related_name='assigned_doctors', to='patients.patient')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
